name: Deploy to GitHub Pages

on:
 push:
  branches:
   - master

jobs:
  spell_check:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v3.0.0
      with:
        # submodules: true
        fetch-depth: 1

    - name: Install cspell
      run: npm install -g cspell@latest

    - name: Spell check
      run: cspell .

  deploy:
    name: Publish site
    runs-on: ubuntu-latest
    needs: spell_check
    steps:
    - name: Checkout main
      uses: actions/checkout@v3.0.0
      with:
        submodules: true
        fetch-depth: 1
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.19.2
      env:
        env: prod
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
