name: Deploy to GitHub Pages

on:
 push:
  branches:
   - master

jobs:
  spell_check:
    name: Spell check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        fetch-depth: 1

    - name: Install cspell
      run: npm install -g cspell@latest

    - name: Spell check
      run: cspell .

  link_check:
    name: Link check
    runs-on: ubuntu-latest
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        fetch-depth: 1
        submodules: true

    - uses: cargo-bins/cargo-binstall@main


    - name: Install lychee
      run: |
        sudo apt-get install gcc pkg-config libc6-dev libssl-dev -y
        cargo binstall lychee sitemap2urllist

    - uses: taiki-e/install-action@v2
      with:
        tool: zola@0.19.2

    - name: Link check
      run: |
        zola serve &
        sleep 3
        sitemap2urllist http://127.0.0.1:1111/sitemap.xml | xargs lychee --exclude linkedin.com --exclude archive.is -a 429
      env:
        GITHUB_TOKEN: ${{ github.token }}

  deploy:
    name: Publish site
    runs-on: ubuntu-latest
    needs: [spell_check, link_check]
    steps:
    - name: Checkout main
      uses: actions/checkout@v4
      with:
        submodules: true
        fetch-depth: 1
    - name: Build and deploy
      uses: shalzz/zola-deploy-action@v0.19.2
      env:
        env: prod
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
